version: 2.1
orbs:
  infracost:
    jobs:
      diff:
        executor: infracost/infracost:latest
        steps:
          - checkout
          - run: infracost --tfdir <<parameters.tfdir>>

workflows:
  main:
    jobs:
      - infracost/diff
