version: 2.1
orbs:
  infracost:
    jobs:
      diff:
        docker:
          - image: infracost/infracost:test
        parameters:
          tfdir:
            type: string
            default: .
            description: The root directory of your terraform file
        steps:
          - checkout
          - run: /scripts/ci/diff.sh "" "" "" << parameters.tfdir >> "" 1 ""

workflows:
  main:
    jobs:
      - infracost/diff:
          tfdir: aws
