version: 2.1
orbs:
  infracost:
    jobs:
      diff:
        docker:
          - image: infracost/infracost:latest
        parameters:
          tfdir:
            type: string
            default: .
            description: The root directory of your terraform file
        steps:
          - checkout
          - run: infracost --tfdir << parameters.tfdir >>
          - run: git switch main
          - run: infracost --tfdir << parameters.tfdir >>

workflows:
  main:
    jobs:
      - infracost/diff:
          tfdir: aws
